### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by machadomatt** [robertgr991/php-parameter-hint#9]
Hi. I've noticed high CPU usage from VS Code using the extension while working with PHP files.

When I start VS Code without any PHP file open, the CPU usage is normal, almost 0% after cache CSS and JS, but when I open a PHP file from the project, the CPU usage goes to 50% and after the parameters are load it goes down to 30%. Closing the file and even reloading the window the CPU does not go down, only after I close VS Code completely and start again without any PHP file open.
I did the same process but with the extension disabled, and the CPU usage with the PHP file open was almost 0%.

Extesion enabled:
![image](https://user-images.githubusercontent.com/47466238/92941396-b15fc680-f426-11ea-8113-f33ddef7ee57.png)

Extension disabled:
![image](https://user-images.githubusercontent.com/47466238/92941525-df450b00-f426-11ea-8607-e03bf899e140.png)

I tried to debug the JS performance with _Running Extensions_ and start debugging, and noticed that the extension is in process all the time after opening the file and even after closing it.

![image](https://user-images.githubusercontent.com/47466238/92941610-fedc3380-f426-11ea-9ce0-07dd79948712.png)

I really like this extension, it's a great helper and I would not like to stop using it.

OS: Windows 10 Pro 64-bit
RAM: 16 GB
CPU: Intel Core i5-4590
VS Code version: 1.49.0
Node version: 12.14.1
PHP version: 7.3.12
PHP Parameter Hint version: 0.5.0

**Comment by robertgr991** [comment]
Hi @machadomatt ,

I will look into it these days, in order to narrow it down, please answer the following:

- Is this problem only with the latest version or did you encounter this since you first installed the extension?
- Does the CPU still goes to 50% and than to 30% if the PHP file that you open has very few possible arguments hints? Or it seems to be independent of the number of possible arguments hints?
- Can you do the same steps but with the extension disabled by command(CTRL + K H) and see if the CPU still goes up? Basically the extension is still active but won't try to hint anything.
- Are you using the default settings?

Some methods are still called even if the current active file is not a PHP file and even if you close all PHP files, but it's basically only some if's, the actual hinting is not happening because there is a check for PHP file. This is the expected behaviour.

The CPU usage is clearly abnormal.

**Comment by machadomatt** [comment]
> * Is this problem only with the latest version or did you encounter this since you first installed the extension?

I can't remember exactly if it was happening when I first install but I noticed it about 2 months ago.

> * Does the CPU still goes to 50% and than to 30% if the PHP file that you open has very few possible arguments hints? Or it seems to be independent of the number of possible arguments hints?

It's independent, tried an one file project with one function and one argument, the CPU usage was the same for a large file with dozens of arguments hints.

> * Can you do the same steps but with the extension disabled by command(CTRL + K H) and see if the CPU still goes up? Basically the extension is still active but won't try to hint anything.

Even disabling with the `CTRL + K H` shortcut the CPU usage is still the same as if it was enabled.

> * Are you using the default settings?

I am using `"phpParameterHint.onSave": false` and `"phpParameterHint.onChange": true`. Disabling them doesn't change the CPU usage.

PS: I did all steps with `0.3.4`, `0.4.1` and `0.5.0` versions.

**Comment by robertgr991** [comment]
Thanks for the info, I'll look into it. It's strange that I know 3 similar extensions and all of them have an issue with CPU usage.

**Comment by robertgr991** [comment]
@machadomatt So it seems that `js-coroutines` package was causing the high CPU usage, it's strange that just by importing it, the CPU went to 30%, without using anything from the module. Can you confirm that the last version `0.5.1` doesn't have this problem?

**Comment by machadomatt** [comment]
Nice! Everything looks good, tested large files and after file processing the CPU usage goes down to 2%, as expected.

Thank you!!

**Comment by robertgr991** [comment]
Great! Thanks for pointing this issue out.
